#!/usr/bin/env python3
"""
CDR Demo — Generate offline sample outputs.

Produces:
    examples/output/sample_report.json   (schema-valid)
    examples/output/sample_report.md     (human-readable render)

This is the script behind `make demo`. It runs WITHOUT any API keys
by using the bundled sample data.

Usage:
    PYTHONPATH=src python scripts/generate_demo.py
"""

from __future__ import annotations

import json
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SAMPLE_JSON = ROOT / "examples" / "output" / "sample_report.json"
SAMPLE_MD = ROOT / "examples" / "output" / "sample_report.md"
SCHEMA_PATH = ROOT / "schemas" / "report.schema.json"


def validate_schema(report: dict) -> bool:
    """Validate report against JSON Schema."""
    try:
        import jsonschema

        schema = json.loads(SCHEMA_PATH.read_text())
        jsonschema.validate(report, schema)
        return True
    except ImportError:
        print("  ⚠️  jsonschema not installed — skipping validation")
        return True
    except Exception as e:
        print(f"  ❌ Schema validation failed: {e}")
        return False


def render_markdown(report: dict) -> str:
    """Render a JSON report as human-readable Markdown."""
    lines = [
        "# CDR Report — Sample Output",
        "",
        f"> **Question**: {report.get('question', 'N/A')}",
        f">",
        f"> **Status**: `{report.get('status', 'unknown')}`  ",
        f"> **Run ID**: `{report.get('run_id', 'N/A')}`  ",
        f"> **Generated**: {report.get('timestamp', 'N/A')}",
        "",
        "---",
        "",
        f"⚠️ {report.get('disclaimer', '')}",
        "",
        "---",
        "",
        "## PICO",
        "",
    ]

    pico = report.get("pico", {})
    lines.extend(
        [
            f"| Component | Value |",
            f"|-----------|-------|",
            f"| **Population** | {pico.get('population', 'N/A')} |",
            f"| **Intervention** | {pico.get('intervention', 'N/A')} |",
            f"| **Comparator** | {pico.get('comparator', 'N/A')} |",
            f"| **Outcome** | {pico.get('outcome', 'N/A')} |",
            "",
        ]
    )

    # PRISMA
    prisma = report.get("prisma_counts", {})
    if prisma:
        lines.extend(
            [
                "## PRISMA Flow",
                "",
                f"- Records identified: **{prisma.get('records_identified', 0)}**",
                f"- Records screened: **{prisma.get('records_screened', 0)}**",
                f"- Full-text assessed: **{prisma.get('full_text_assessed', 0)}**",
                f"- Studies included: **{prisma.get('studies_included', 0)}**",
                "",
            ]
        )

    # Claims
    claims = report.get("claims", [])
    if claims:
        lines.extend(
            [
                f"## Evidence Claims ({len(claims)})",
                "",
            ]
        )
        for i, c in enumerate(claims, 1):
            cert = c.get("certainty", "?").upper()
            verified = "✅" if c.get("verified") else "❌" if c.get("verified") is False else "?"
            snippets = len(c.get("supporting_snippet_ids", []))
            lines.extend(
                [
                    f"### Claim {i} [{cert}] {verified}",
                    "",
                    f"> {c.get('claim_text', '')}",
                    "",
                    f"*Supporting snippets: {snippets} | Context: {c.get('therapeutic_context', 'N/A')}*",
                    "",
                ]
            )

    # KPIs
    kpis = report.get("run_kpis", {})
    if kpis:
        lines.extend(
            [
                "## Quality KPIs",
                "",
                "| Metric | Value |",
                "|--------|-------|",
            ]
        )
        for k, v in kpis.items():
            label = k.replace("_", " ").title()
            val = f"{v:.2%}" if isinstance(v, float) else str(v)
            lines.append(f"| {label} | {val} |")
        lines.append("")

    # Answer
    answer = report.get("answer", "")
    if answer:
        lines.extend(
            [
                "## Summary Answer",
                "",
                answer,
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            f"*Generated by CDR v0.1 · [Report Anatomy](../../docs/report_anatomy.md)*",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    print("🔬  CDR Demo — Offline Sample Generation")
    print("=" * 50)
    print()

    # Load existing sample report
    if not SAMPLE_JSON.exists():
        print(f"❌  Sample report not found: {SAMPLE_JSON}")
        return 1

    report = json.loads(SAMPLE_JSON.read_text())
    print(f"  ✅ Loaded {SAMPLE_JSON.name}")
    print(f"     Question: {report.get('question', 'N/A')[:60]}...")
    print(f"     Status:   {report.get('status', 'unknown')}")
    print(f"     Claims:   {report.get('claim_count', 0)}")
    print(f"     Studies:  {report.get('study_count', 0)}")
    print()

    # Validate against schema
    print("  🔍 Validating against schemas/report.schema.json...")
    if not validate_schema(report):
        return 1
    print("  ✅ Schema validation passed")
    print()

    # Render Markdown
    md_content = render_markdown(report)
    SAMPLE_MD.write_text(md_content)
    print(f"  ✅ Rendered {SAMPLE_MD.name} ({len(md_content)} bytes)")
    print()

    print("📋  Outputs:")
    print(f"    JSON: {SAMPLE_JSON.relative_to(ROOT)}")
    print(f"    MD:   {SAMPLE_MD.relative_to(ROOT)}")
    print()
    print("✅  Demo complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
